name: Tests

on:
  # Allow to manually trigger through github API
  workflow_dispatch:

  # Triggers with push to master
  push:
    branches:
      - master

  # Triggers with push to a pr aimed at master
  pull_request:
    branches:
      - master

  schedule:
    # https://crontab.guru/#42_2_3_*_*
    # "At 02:42 on day-of-month 3"
    # Put it at this odd time to reduce competing with load spikes on github action servers
    - cron: '42 2 3 * *'

env:

  import-package-name: grakel
  test-dir: tests

  codecov-py: "3.10"
  codecov-args: >-
    --cov=grakel
    --cov-report=xml

jobs:

  # General unit tests
  source-test:
    name: ${{ matrix.py }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash # Default to using bash on all

    strategy:
      fail-fast: false
      matrix:
        py: ["3.10", "3.11", "3.12", "3.13"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}

    - name: Install ${{ env.import-package-name }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --with test

    - name: Ensure setuptools and wheel are installed
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel

    - name: Build Cython extensions
      run: |
        poetry run python setup.py build_ext --inplace

    - name: Tests
      run: |
        poetry run pytest # ${{ env.test-dir }}

  # Testing with codecov coverage uploaded
  codecov-test:
    name: codecov-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.codecov-py }}

    - name: Install ${{ env.import-package-name }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --with test

    - name: Ensure setuptools and wheel are installed
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel

    - name: Build Cython extensions
      run: |
        poetry run python setup.py build_ext --inplace

    - name: Tests
      run: |
        poetry run pytest ${{ env.codecov-args }} ${{ env.test-dir }}

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      # Only upload coverage when it's **not** a scheduled test run
      if: ${{ ! github.event.schedule }}
      with:
        fail_ci_if_error: true
        verbose: true
